[package]
name = "seify"
version = "0.5.1"
description = "Shiny Samples from your Rusty SDR"
documentation = "https://docs.rs/seify/"
edition = "2021"
homepage = "https://www.futuresdr.org"
license = "Apache-2.0"
repository = "https://github.com/FutureSDR/seify"

[features]
default = ["soapy"]
rtlsdr = ["dep:seify-rtlsdr"]
aaronia = ["dep:aaronia-rtsa"]
aaronia_http = ["dep:ureq"]
soapy = ["dep:soapysdr"]

[dependencies]
futures = "0.3.28"
log = "0.4.17"
nom = "7.1"
num-complex = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.0"
thiserror = "1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
once_cell = "1.17"
seify-rtlsdr = { path = "crates/rtl-sdr-rs", version = "0.0.1", optional = true }
soapysdr = { version = "0.3.2", optional = true }
ureq = { version = "2.6", features = ["json"], optional = true }

[target.'cfg(any(target_os = "linux", target_os= "windows"))'.dependencies]
aaronia-rtsa = { version = "0.0.6", optional = true }

[dev-dependencies]
clap = { version = "4.2", features = ["derive"] }
env_logger = "0.10.0"
gnuplot = "0.0.38"
rustfft = "6.1"
vmcircbuffer = "0.0.9"

[package.metadata.docs.rs]
no-default-features = true
